### PR TITLE
Muzzle flash

### PR DESCRIPTION
**Pull request by scottnm**

### CODE REVIEW

**Comment by phoenixbishea** [comment]
The muzzle flash appears to being playing twice. Or at least once and a half. So it is large, then small, and then large again. Also check the bullet layer to be sure it is behind the muzzle flash. Should it be behind the gun as well?

**Comment by phoenixbishea** [comment]
Also, should we keep the fire works effect for the veto?

**Comment by scottnm** [comment]
I took the firework effect off the veto already I believe

**Comment by scottnm** [comment]
this pull request report seems to not be updating for me, but I pushed up two changes that fix the animation running twice and fix the order of the flash, bullet, and gun

**Comment by phoenixbishea** [comment]
Oh my question earlier was if we should use the fireworks in addition to the muzzle flash? Like if we should add them back in? Depending on that, it looks good.

**Comment by scottnm** [comment]
Cool. I decided against using both for consistencies sake

**Pull request merged**
