### PR TITLE
Added some helpful build scripts

### PR DESCRIPTION
**Pull request by scottnm**
Added some build scripts so that I can quickly build for windows, mac, or both. Also gives the ability to build and run two clients quickly to reduce testing time

### CODE REVIEW

**Comment by scottnm** [comment]
Whoops totally didn't see these comments. Not sure how I missed them. Could you better define what you mean by dynamically find scenes? What kind of behavior are you looking for? Like when I hit the build button you want a window to appear that lets you select different scenes? or do you just not want the scenes selected as hardcoded strings? I figured the build options were for building the full build so defining them as strings wasn't a big deal and we'd only need to update the list of strings when we change what is in the full build.

**Comment by phoenixbishea** [comment]
image

I meant not having them hardcoded as strings. I'm not sure how hard it would be to emulate something like the image above. We can look into it at a later sprint.

**Comment by phoenixbishea** [comment]
Or just a simple menu item that allows you to select from existing scenes.

**Comment by scottnm** [comment]
For me the purpose of having the build menu items was for quick rapid building. I hardcoded the build options because that is what I will be building 90% of the time. If I add a menu and set of customizable options I worry that I'd just be recreating the build options that already exists. I agree that we should table this for another sprint

**Pull request merged**
