### PR TITLE
Added effect for when bullet hits a wall

### PR DESCRIPTION
**Pull request by scottnm**

### CODE REVIEW

**Comment by phoenixbishea** [comment]
Hey I made a change to use quaternion rotation versus euler angle rotation. When the normal was (0, 1) the dust effect was getting a rotation of 90 (versus -90) so the particle effect was facing the wrong way. Additionally, I think you were cumulatively rotating the pool of particle effects. Quaternions should fix both of these problems.

**Comment by scottnm** [comment]
👌 killer

**Review by phoenixbishea — APPROVED** [review]
If my changes look alright, then this one is good to merge in.

**Comment by scottnm** [comment]
yeah your changes are good! (wasn't sure if I should mark them approved or if that'd be weird on my own pull request. Just so I understand one of my own issues though. When you said culmulatively rotating the fx pool. You meant that calling Rotate wasn't setting a rotation, but adding an additional rotation right?

**Pull request merged**
