### PR TITLE
Integrate new sprite sheets

### PR DESCRIPTION
**Pull request by scottnm**

### CODE REVIEW

**Comment by scottnm** [comment]
code changes are localized to commit f78c384. Look at SpawnManager, CharacterSelectManager, and Utility. Everything else is just animator, animation, and net player prefab changes

**Comment by phoenixbishea** [comment]
I'm good to approve this one after two things:

1. Get the green guy in before you merge
2. When the woman switches sides there is a noticeable delay of her eye changing. Is this possible to fix?

**Comment by phoenixbishea** [comment]
Also, we may need add the second arm supporting weapons in the background. It's more noticeable on the female. But don't worry about this for now unless it's quick.

**Comment by scottnm** [comment]
I added the back arm issue and the head turning eyeball issue to zenhub. Don't want to fix right now since we are down to the wire with this sprint

**Pull request merged**
